/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Armas.ArmaAbstracta;
import Cuerpos.CuerpoAbstracto;
import Escudos.EscudoAbstracto;
import Fabricas.FabricaElfos;
import Fabricas.FabricaMagos;
import Fabricas.FabricaPersonajes;
import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.*;

/**
 *
 * @author estudiantes
 */
public class FRM_Principal extends javax.swing.JFrame {

    private static FRM_Principal GUI;

    private Image imagen;
    imagenfondo image = new imagenfondo();
    Font fuente = new Font("Dialog", Font.BOLD, 20);

    ArmaAbstracta Arma;
    CuerpoAbstracto Cuerpo;
    EscudoAbstracto Escudo;

    private FRM_Principal() {
        super("eleccion de personaje");
        initComponents();
        setResizable(false);
        super.setLocationRelativeTo(null);
        image.setImage("/Rescursos/fondo.png");
        image.setLayout(null);
        setContentPane(image);
        image.add(mago);
        image.add(elfo);
        image.add(elfoLabel);
        image.add(magoLabel);
        image.add(titulo);
        textoArma.setOpaque(false);
        textoArma.setBackground(new Color(0, 0, 0, 0));
        textoArma.setBounds(450, 100, 100, 100);
        textoArma.setFont(fuente);
        textoEscudo.setOpaque(false);
        textoEscudo.setBackground(new Color(0, 0, 0, 0));
        textoEscudo.setBounds(950, 100, 100, 100);
        textoEscudo.setFont(fuente);
        textoCuepos.setOpaque(false);
        textoCuepos.setBackground(new Color(0, 0, 0, 0));
        textoCuepos.setBounds(600, 550, 100, 100);
        textoCuepos.setFont(fuente);
    }

    public static FRM_Principal getInstance() {
        if (GUI == null) {
            GUI = new FRM_Principal();
        }
        return GUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mago = new javax.swing.JLabel();
        elfo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        magoLabel = new javax.swing.JLabel();
        elfoLabel = new javax.swing.JLabel();
        dagita = new javax.swing.JLabel();
        escudito = new javax.swing.JLabel();
        pocioncitas = new javax.swing.JLabel();
        varitita = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArma = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoCuepos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoEscudo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1421, 700));
        setSize(new java.awt.Dimension(1421, 700));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/hechizero.png"))); // NOI18N
        mago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magoMouseClicked(evt);
            }
        });
        getContentPane().add(mago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 139, -1, -1));

        elfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/elfo.png"))); // NOI18N
        elfo.setMaximumSize(new java.awt.Dimension(195, 402));
        elfo.setMinimumSize(new java.awt.Dimension(195, 402));
        elfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elfoMouseClicked(evt);
            }
        });
        getContentPane().add(elfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 226, -1, -1));

        titulo.setBackground(new java.awt.Color(102, 255, 102));
        titulo.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 255, 51));
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/titulouwu.PNG"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1411, 160));

        magoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/magouwu.PNG"))); // NOI18N
        getContentPane().add(magoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 587, -1, 81));

        elfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/elfouwu.PNG"))); // NOI18N
        getContentPane().add(elfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 587, 163, 70));

        dagita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/daga.png"))); // NOI18N
        getContentPane().add(dagita, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 467, 0, 0));

        escudito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/escudo.png"))); // NOI18N
        getContentPane().add(escudito, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 164, 0, 0));

        pocioncitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/pociones.png"))); // NOI18N
        getContentPane().add(pocioncitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 443, 0, 0));

        varitita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/varita.png"))); // NOI18N
        getContentPane().add(varitita, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 467, 0, 0));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rescursos/return.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 416, 0, 0));

        textoArma.setEditable(false);
        textoArma.setColumns(20);
        textoArma.setRows(5);
        textoArma.setText("saldkñlaskdñasldkfñasdf\ndasf\nasd\nfasd\nf\nasd\nfasdfsadfas\ndf\nas\ndfasdf");
        textoArma.setEnabled(false);
        jScrollPane1.setViewportView(textoArma);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 431, 0, 0));

        textoCuepos.setEditable(false);
        textoCuepos.setColumns(20);
        textoCuepos.setRows(5);
        textoCuepos.setText("dasdasdasdadsadsdassadsda\nadsadsdsadsadsasddsasaddsa\nsaddasdsaadsdsaadssdadsasda\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa");
        textoCuepos.setEnabled(false);
        jScrollPane2.setViewportView(textoCuepos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 424, 0, 0));

        textoEscudo.setEditable(false);
        textoEscudo.setColumns(20);
        textoEscudo.setRows(5);
        textoEscudo.setText("dsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa\ndsasdadsadsadsaadsdsadasdsa");
        textoEscudo.setEnabled(false);
        textoEscudo.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(textoEscudo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 457, 0, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elfoMouseClicked
        image.removeAll();

        FabricaPersonajes Fabrica = new FabricaElfos();
        Arma = Fabrica.CrearArma();
        Cuerpo = Fabrica.CrearCuerpo();
        Escudo = Fabrica.CrearEscudo();

        setSize(1500, 1000);
        setLocationRelativeTo(null);
        escudito.setBounds(700, 1, 500, 500);
        dagita.setBounds(50, 1, 500, 500);
        elfo.setBounds(300, 550, 218, 315);
        volver.setBounds(50, 500, 500, 500);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBackground(new Color(0, 0, 0, 0));
        image.add(dagita);
        image.add(escudito);
        image.add(elfo);
        image.add(volver);

        textoArma.setOpaque(false);
        textoArma.setBackground(new Color(0, 0, 0, 0));
        textoArma.setBounds(350, 100, 500, 500);
        textoArma.setFont(fuente);
        textoArma.setText(Arma.getMensaje());

        textoEscudo.setOpaque(false);
        textoEscudo.setBackground(new Color(0, 0, 0, 0));
        textoEscudo.setBounds(1050, 100, 500, 500);
        textoEscudo.setFont(fuente);
        textoEscudo.setText(Escudo.getMensaje());

        textoCuepos.setOpaque(false);
        textoCuepos.setBackground(new Color(0, 0, 0, 0));
        textoCuepos.setBounds(600, 550, 700, 300);
        textoCuepos.setFont(fuente);
        textoCuepos.setText(Cuerpo.getMensaje());

        image.add(textoArma);
        image.add(textoEscudo);
        image.add(textoCuepos);
        image.revalidate();
        image.repaint();
    }//GEN-LAST:event_elfoMouseClicked


    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        image.removeAll();
        elfo.setLocation(38, 226);
        mago.setLocation(1167, 139);
        setSize(1421, 700);
        setLocationRelativeTo(null);
        image.add(mago);
        image.add(elfo);
        image.add(elfoLabel);
        image.add(magoLabel);
        image.add(titulo);
        image.revalidate();
        image.repaint();
    }//GEN-LAST:event_volverMouseClicked

    private void magoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magoMouseClicked
        image.removeAll();

        FabricaPersonajes Fabrica = new FabricaMagos();
        Arma = Fabrica.CrearArma();
        Cuerpo = Fabrica.CrearCuerpo();
        Escudo = Fabrica.CrearEscudo();

        setSize(1500, 1000);
        setLocationRelativeTo(null);
        pocioncitas.setBounds(730, 1, 500, 500);
        varitita.setBounds(50, 1, 500, 500);
        mago.setBounds(300, 550, 218, 405);
        volver.setBounds(50, 500, 500, 500);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBackground(new Color(0, 0, 0, 0));

        image.add(pocioncitas);
        image.add(varitita);
        image.add(mago);
        image.add(volver);

        textoArma.setOpaque(false);
        textoArma.setBackground(new Color(0, 0, 0, 0));
        textoArma.setBounds(320, 100, 500, 500);
        textoArma.setFont(fuente);
        textoArma.setText(Arma.getMensaje());

        textoEscudo.setOpaque(false);
        textoEscudo.setBackground(new Color(0, 0, 0, 0));
        textoEscudo.setBounds(1050, 100, 500, 500);
        textoEscudo.setFont(fuente);
        textoEscudo.setText(Escudo.getMensaje());

        textoCuepos.setOpaque(false);
        textoCuepos.setBackground(new Color(0, 0, 0, 0));
        textoCuepos.setBounds(600, 550, 710, 300);
        textoCuepos.setFont(fuente);
        textoCuepos.setText(Cuerpo.getMensaje());

        image.add(textoArma);
        image.add(textoEscudo);
        image.add(textoCuepos);
        image.revalidate();
        image.repaint();
    }//GEN-LAST:event_magoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dagita;
    private javax.swing.JLabel elfo;
    private javax.swing.JLabel elfoLabel;
    private javax.swing.JLabel escudito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mago;
    private javax.swing.JLabel magoLabel;
    private javax.swing.JLabel pocioncitas;
    private javax.swing.JTextArea textoArma;
    private javax.swing.JTextArea textoCuepos;
    private javax.swing.JTextArea textoEscudo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel varitita;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables

}
